(* Generated by candle_insulate.py based on CakeML's types.txt *)
(* This file insulates the codebase from direct CakeML API usage *)

module Cake = struct
  module Alist = struct
    let delete x0 x1 = Alist.delete x0 x1
    let every x0 x1 = Alist.every x0 x1
    let lookup x0 x1 = Alist.lookup x0 x1
    let map x0 x1 = Alist.map x0 x1
    let update x0 x1 = Alist.update x0 x1
  end;;

  module Array = struct
    let all x0 x1 = Array.all x0 x1
    let app x0 x1 = Array.app x0 x1
    let appi x0 x1 = Array.appi x0 x1
    let array x0 x1 = Array.array x0 x1
    let arrayEmpty x0 = Array.arrayEmpty x0
    let collate x0 x1 x2 = Array.collate x0 x1 x2
    let copy x0 x1 x2 = Array.copy x0 x1 x2
    let copyVec x0 x1 x2 = Array.copyVec x0 x1 x2
    let exists x0 x1 = Array.exists x0 x1
    let find x0 x1 = Array.find x0 x1
    let findi x0 x1 = Array.findi x0 x1
    let foldl x0 x1 x2 = Array.foldl x0 x1 x2
    let foldli x0 x1 x2 = Array.foldli x0 x1 x2
    let foldr x0 x1 x2 = Array.foldr x0 x1 x2
    let foldri x0 x1 x2 = Array.foldri x0 x1 x2
    let fromList x0 = Array.fromList x0
    let length x0 = Array.length x0
    let lookup x0 x1 x2 = Array.lookup x0 x1 x2
    let modify x0 x1 = Array.modify x0 x1
    let modifyi x0 x1 = Array.modifyi x0 x1
    let sub x0 x1 = Array.sub x0 x1
    let tabulate x0 x1 = Array.tabulate x0 x1
    let update x0 x1 x2 = Array.update x0 x1 x2
    let updateResize x0 x1 x2 x3 = Array.updateResize x0 x1 x2 x3
  end;;

  module Bool = struct
    let (=) x0 x1 = Bool.(=) x0 x1
    let compare x0 x1 = Bool.compare x0 x1
    let fromString x0 = Bool.fromString x0
    let not x0 = Bool.not x0
    let toString x0 = Bool.toString x0
  end;;

  module Char = struct
    let (<) x0 x1 = Char.(<) x0 x1
    let (<=) x0 x1 = Char.(<=) x0 x1
    let (=) x0 x1 = Char.(=) x0 x1
    let (>) x0 x1 = Char.(>) x0 x1
    let (>=) x0 x1 = Char.(>=) x0 x1
    let chr x0 = Char.chr x0
    let fromByte x0 = Char.fromByte x0
    let isSpace x0 = Char.isSpace x0
    let ord x0 = Char.ord x0
    let some x0 = Char.some x0
  end;;

  module Command_line = struct
    let arguments x0 = Command_line.arguments x0
    let cline x0 = Command_line.cline x0
    let name x0 = Command_line.name x0
  end;;

  module Double = struct
    type double = Double.double

    let ( * ) x0 x1 = Double.( * ) x0 x1
    let (+) x0 x1 = Double.(+) x0 x1
    let (-) x0 x1 = Double.(-) x0 x1
    let (/) x0 x1 = Double.(/) x0 x1
    let (<) x0 x1 = Double.(<) x0 x1
    let (<=) x0 x1 = Double.(<=) x0 x1
    let (=) x0 x1 = Double.(=) x0 x1
    let (>) x0 x1 = Double.(>) x0 x1
    let (>=) x0 x1 = Double.(>=) x0 x1
    let abs x0 = Double.abs x0
    let construct x0 x1 x2 = Double.construct x0 x1 x2
    let exp x0 = Double.exp x0
    let exponent x0 = Double.exponent x0
    let ffloat_ulp x0 = Double.ffloat_ulp x0
    let float_is_finite x0 = Double.float_is_finite x0
    let float_is_zero x0 = Double.float_is_zero x0
    let floor x0 = Double.floor x0
    let flt_max = Double.flt_max
    let fma x0 x1 x2 = Double.fma x0 x1 x2
    let fnext_hi x0 = Double.fnext_hi x0
    let fnext_lo x0 = Double.fnext_lo x0
    let fromInt x0 = Double.fromInt x0
    let fromString x0 = Double.fromString x0
    let fromWord x0 = Double.fromWord x0
    let ln x0 = Double.ln x0
    let maxulp = Double.maxulp
    let neginf64 = Double.neginf64
    let posinf64 = Double.posinf64
    let posmin64 = Double.posmin64
    let poszero64 = Double.poszero64
    let pow x0 x1 = Double.pow x0 x1
    let pp_double x0 = Double.pp_double x0
    let sign x0 = Double.sign x0
    let significand x0 = Double.significand x0
    let sqrt x0 = Double.sqrt x0
    let toInt x0 = Double.toInt x0
    let toString x0 = Double.toString x0
    let toWord x0 = Double.toWord x0
    let twicemaxulp = Double.twicemaxulp
  end;;

  module Hashtable = struct
    let clear x0 = Hashtable.clear x0
    let delete x0 x1 = Hashtable.delete x0 x1
    let empty x0 x1 x2 = Hashtable.empty x0 x1 x2
    let insert x0 x1 x2 = Hashtable.insert x0 x1 x2
    let lookup x0 x1 = Hashtable.lookup x0 x1
    let size x0 = Hashtable.size x0
    let toAscList x0 = Hashtable.toAscList x0
  end;;

  module Int = struct
    let ( * ) x0 x1 = Int.( * ) x0 x1
    let (+) x0 x1 = Int.(+) x0 x1
    let (-) x0 x1 = Int.(-) x0 x1
    let (<) x0 x1 = Int.(<) x0 x1
    let (<=) x0 x1 = Int.(<=) x0 x1
    let (>) x0 x1 = Int.(>) x0 x1
    let (>=) x0 x1 = Int.(>=) x0 x1
    let (mod) x0 x1 = Int.(mod) x0 x1
    let compare x0 x1 = Int.compare x0 x1
    let div x0 x1 = Int.div x0 x1
    let fromNatString x0 = Int.fromNatString x0
    let fromString x0 = Int.fromString x0
    let gcd x0 x1 = Int.gcd x0 x1
    let int_to_string x0 x1 = Int.int_to_string x0 x1
    let toString x0 = Int.toString x0
  end;;

  module List = struct
    let (@) x0 x1 = List.(@) x0 x1
    let all x0 x1 = List.all x0 x1
    let all_distinct x0 = List.all_distinct x0
    let app x0 x1 = List.app x0 x1
    let cmp x0 x1 x2 = List.cmp x0 x1 x2
    let collate x0 x1 x2 = List.collate x0 x1 x2
    let compare x0 x1 x2 = List.compare x0 x1 x2
    let concat x0 = List.concat x0
    let drop x0 x1 = List.drop x0 x1
    let dropUntil x0 x1 = List.dropUntil x0 x1
    let exists x0 x1 = List.exists x0 x1
    let filter x0 x1 = List.filter x0 x1
    let filterRev x0 x1 = List.filterRev x0 x1
    let find x0 x1 = List.find x0 x1
    let flatRev x0 = List.flatRev x0
    let foldl x0 x1 x2 = List.foldl x0 x1 x2
    let foldli x0 x1 x2 = List.foldli x0 x1 x2
    let foldr x0 x1 x2 = List.foldr x0 x1 x2
    let foldri x0 x1 x2 = List.foldri x0 x1 x2
    let front x0 = List.front x0
    let genlist x0 x1 = List.genlist x0 x1
    let getItem x0 = List.getItem x0
    let hd x0 = List.hd x0
    let isPrefix x0 x1 = List.isPrefix x0 x1
    let last x0 = List.last x0
    let length x0 = List.length x0
    let map x0 x1 = List.map x0 x1
    let mapPartial x0 x1 = List.mapPartial x0 x1
    let mapRev x0 x1 = List.mapRev x0 x1
    let mapi x0 x1 = List.mapi x0 x1
    let member x0 x1 = List.member x0 x1
    let nth x0 x1 = List.nth x0 x1
    let null x0 = List.null x0
    let pad_left x0 x1 x2 = List.pad_left x0 x1 x2
    let pad_right x0 x1 x2 = List.pad_right x0 x1 x2
    let partition x0 x1 = List.partition x0 x1
    let rev x0 = List.rev x0
    let snoc x0 x1 = List.snoc x0 x1
    let sort x0 x1 = List.sort x0 x1
    let split x0 x1 = List.split x0 x1
    let splitAtPki x0 x1 x2 = List.splitAtPki x0 x1 x2
    let sum x0 = List.sum x0
    let tabulate x0 x1 = List.tabulate x0 x1
    let take x0 x1 = List.take x0 x1
    let takeUntil x0 x1 = List.takeUntil x0 x1
    let tl x0 = List.tl x0
    let unzip x0 = List.unzip x0
    let update x0 x1 x2 = List.update x0 x1 x2
    let zip x0 = List.zip x0
  end;;

  module Map = struct
    let all x0 x1 = Map.all x0 x1
    let compare x0 x1 x2 = Map.compare x0 x1 x2
    let delete x0 x1 = Map.delete x0 x1
    let empty x0 = Map.empty x0
    let exists x0 x1 = Map.exists x0 x1
    let filter x0 x1 = Map.filter x0 x1
    let filterWithKey x0 x1 = Map.filterWithKey x0 x1
    let foldrWithKey x0 x1 x2 = Map.foldrWithKey x0 x1 x2
    let fromList x0 x1 = Map.fromList x0 x1
    let insert x0 x1 x2 = Map.insert x0 x1 x2
    let isSubmap x0 x1 = Map.isSubmap x0 x1
    let isSubmapBy x0 x1 x2 = Map.isSubmapBy x0 x1 x2
    let lookup x0 x1 = Map.lookup x0 x1
    let map x0 x1 = Map.map x0 x1
    let mapWithKey x0 x1 = Map.mapWithKey x0 x1
    let member x0 x1 = Map.member x0 x1
    let null x0 = Map.null x0
    let singleton x0 x1 x2 = Map.singleton x0 x1 x2
    let size x0 = Map.size x0
    let toAscList x0 = Map.toAscList x0
    let union x0 x1 = Map.union x0 x1
    let unionWith x0 x1 x2 = Map.unionWith x0 x1 x2
    let unionWithKey x0 x1 x2 = Map.unionWithKey x0 x1 x2
  end;;

  module Marshalling = struct
    let n2w2 x0 x1 x2 = Marshalling.n2w2 x0 x1 x2
    let w22n x0 x1 = Marshalling.w22n x0 x1
  end;;

  module Option = struct
    let compare x0 x1 x2 = Option.compare x0 x1 x2
    let compose x0 x1 x2 = Option.compose x0 x1 x2
    let composePartial x0 x1 x2 = Option.composePartial x0 x1 x2
    let getOpt x0 x1 = Option.getOpt x0 x1
    let isNone x0 = Option.isNone x0
    let isSome x0 = Option.isSome x0
    let join x0 = Option.join x0
    let map x0 x1 = Option.map x0 x1
    let map2 x0 x1 x2 = Option.map2 x0 x1 x2
    let mapPartial x0 x1 = Option.mapPartial x0 x1
    let valOf x0 = Option.valOf x0
  end;;

  module Pair = struct
    let compare x0 x1 x2 x3 = Pair.compare x0 x1 x2 x3
    let map x0 x1 x2 = Pair.map x0 x1 x2
    let toString x0 x1 x2 = Pair.toString x0 x1 x2
  end;;

  module Rat = struct
    type rat = Rat.rat

    let ( * ) x0 x1 = Rat.( * ) x0 x1
    let (+) x0 x1 = Rat.(+) x0 x1
    let (-) x0 x1 = Rat.(-) x0 x1
    let (/) x0 x1 = Rat.(/) x0 x1
    let (<) x0 x1 = Rat.(<) x0 x1
    let (<=) x0 x1 = Rat.(<=) x0 x1
    let (>) x0 x1 = Rat.(>) x0 x1
    let (>=) x0 x1 = Rat.(>=) x0 x1
    let ceiling x0 = Rat.ceiling x0
    let compare x0 x1 = Rat.compare x0 x1
    let denominator x0 = Rat.denominator x0
    let floor x0 = Rat.floor x0
    let fromInt x0 = Rat.fromInt x0
    let inv x0 = Rat.inv x0
    let is_int x0 = Rat.is_int x0
    let max x0 x1 = Rat.max x0 x1
    let min x0 x1 = Rat.min x0 x1
    let numerator x0 = Rat.numerator x0
    let pp_rat x0 = Rat.pp_rat x0
    let toString x0 = Rat.toString x0
  end;;

  module Runtime = struct
    let abort x0 = Runtime.abort x0
    let debugMsg x0 = Runtime.debugMsg x0
    let exit x0 = Runtime.exit x0
    let fail x0 = Runtime.fail x0
    let fullGC x0 = Runtime.fullGC x0
  end;;

  module Set = struct
    let all x0 x1 = Set.all x0 x1
    let compare x0 x1 = Set.compare x0 x1
    let delete x0 x1 = Set.delete x0 x1
    let empty x0 = Set.empty x0
    let exists x0 x1 = Set.exists x0 x1
    let filter x0 x1 = Set.filter x0 x1
    let fold x0 x1 x2 = Set.fold x0 x1 x2
    let fromList x0 x1 = Set.fromList x0 x1
    let insert x0 x1 = Set.insert x0 x1
    let isSubset x0 x1 = Set.isSubset x0 x1
    let map x0 x1 = Set.map x0 x1
    let member x0 x1 = Set.member x0 x1
    let null x0 = Set.null x0
    let singleton x0 x1 = Set.singleton x0 x1
    let size x0 = Set.size x0
    let toList x0 = Set.toList x0
    let translate x0 x1 x2 = Set.translate x0 x1 x2
    let union x0 x1 = Set.union x0 x1
  end;;

  module Sexp = struct
    let fromString x0 = Sexp.fromString x0
    let inputSexp x0 = Sexp.inputSexp x0
    let pp_sexp x0 = Sexp.pp_sexp x0
    let pp_str_tree x0 = Sexp.pp_str_tree x0
    let str_tree_to_strings x0 x1 = Sexp.str_tree_to_strings x0 x1
    let toPrettyString x0 = Sexp.toPrettyString x0
    let toString x0 = Sexp.toString x0
  end;;

  module String = struct
    let (<) x0 x1 = String.(<) x0 x1
    let (<=) x0 x1 = String.(<=) x0 x1
    let (=) x0 x1 = String.(=) x0 x1
    let (>) x0 x1 = String.(>) x0 x1
    let (>=) x0 x1 = String.(>=) x0 x1
    let (^) x0 x1 = String.(^) x0 x1
    let char_escape_seq x0 = String.char_escape_seq x0
    let collate x0 x1 x2 = String.collate x0 x1 x2
    let compare x0 x1 = String.compare x0 x1
    let concat x0 = String.concat x0
    let concatWith x0 x1 = String.concatWith x0 x1
    let escape_char x0 = String.escape_char x0
    let escape_str x0 = String.escape_str x0
    let explode x0 = String.explode x0
    let extract x0 x1 x2 = String.extract x0 x1 x2
    let fields x0 x1 = String.fields x0 x1
    let findi x0 x1 x2 = String.findi x0 x1 x2
    let implode x0 = String.implode x0
    let isPrefix x0 x1 = String.isPrefix x0 x1
    let isSubstring x0 x1 = String.isSubstring x0 x1
    let isSuffix x0 x1 = String.isSuffix x0 x1
    let size x0 = String.size x0
    let split x0 x1 = String.split x0 x1
    let str x0 = String.str x0
    let strcat x0 x1 = String.strcat x0 x1
    let sub x0 x1 = String.sub x0 x1
    let substring x0 x1 x2 = String.substring x0 x1 x2
    let tokens x0 x1 = String.tokens x0 x1
    let translate x0 x1 = String.translate x0 x1
  end;;

  module Vector = struct
    let all x0 x1 = Vector.all x0 x1
    let collate x0 x1 x2 = Vector.collate x0 x1 x2
    let concat x0 = Vector.concat x0
    let exists x0 x1 = Vector.exists x0 x1
    let find x0 x1 = Vector.find x0 x1
    let findi x0 x1 = Vector.findi x0 x1
    let foldl x0 x1 x2 = Vector.foldl x0 x1 x2
    let foldli x0 x1 x2 = Vector.foldli x0 x1 x2
    let foldr x0 x1 x2 = Vector.foldr x0 x1 x2
    let foldri x0 x1 x2 = Vector.foldri x0 x1 x2
    let fromList x0 = Vector.fromList x0
    let length x0 = Vector.length x0
    let map x0 x1 = Vector.map x0 x1
    let mapi x0 x1 = Vector.mapi x0 x1
    let sub x0 x1 = Vector.sub x0 x1
    let tabulate x0 x1 = Vector.tabulate x0 x1
    let toList x0 = Vector.toList x0
    let update x0 x1 x2 = Vector.update x0 x1 x2
  end;;

  module Word64 = struct
    let (+) x0 x1 = Word64.(+) x0 x1
    let (-) x0 x1 = Word64.(-) x0 x1
    let (<) x0 x1 = Word64.(<) x0 x1
    let (<<) x0 x1 = Word64.(<<) x0 x1
    let (<=) x0 x1 = Word64.(<=) x0 x1
    let (=) x0 x1 = Word64.(=) x0 x1
    let (>) x0 x1 = Word64.(>) x0 x1
    let (>=) x0 x1 = Word64.(>=) x0 x1
    let (>>) x0 x1 = Word64.(>>) x0 x1
    let andb x0 x1 = Word64.andb x0 x1
    let concatAll x0 x1 x2 x3 x4 x5 x6 x7 = Word64.concatAll x0 x1 x2 x3 x4 x5 x6 x7
    let fromInt x0 = Word64.fromInt x0
    let notb x0 = Word64.notb x0
    let orb x0 x1 = Word64.orb x0 x1
    let ror x0 x1 = Word64.ror x0 x1
    let toInt x0 = Word64.toInt x0
    let toIntSigned x0 = Word64.toIntSigned x0
    let xorb x0 x1 = Word64.xorb x0 x1
  end;;

  module Word8 = struct
    let (+) x0 x1 = Word8.(+) x0 x1
    let (-) x0 x1 = Word8.(-) x0 x1
    let (<) x0 x1 = Word8.(<) x0 x1
    let (<<) x0 x1 = Word8.(<<) x0 x1
    let (<=) x0 x1 = Word8.(<=) x0 x1
    let (=) x0 x1 = Word8.(=) x0 x1
    let (>) x0 x1 = Word8.(>) x0 x1
    let (>=) x0 x1 = Word8.(>=) x0 x1
    let (>>) x0 x1 = Word8.(>>) x0 x1
    let andb x0 x1 = Word8.andb x0 x1
    let fromInt x0 = Word8.fromInt x0
    let notb x0 = Word8.notb x0
    let orb x0 x1 = Word8.orb x0 x1
    let ror x0 x1 = Word8.ror x0 x1
    let toInt x0 = Word8.toInt x0
    let toIntSigned x0 = Word8.toIntSigned x0
    let xorb x0 x1 = Word8.xorb x0 x1
  end;;

  module Word8_array = struct
    let array x0 x1 = Word8_array.array x0 x1
    let copy x0 x1 x2 x3 x4 = Word8_array.copy x0 x1 x2 x3 x4
    let copyVec x0 x1 x2 x3 x4 = Word8_array.copyVec x0 x1 x2 x3 x4
    let findi x0 x1 = Word8_array.findi x0 x1
    let length x0 = Word8_array.length x0
    let sub x0 x1 = Word8_array.sub x0 x1
    let substring x0 x1 x2 = Word8_array.substring x0 x1 x2
    let update x0 x1 x2 = Word8_array.update x0 x1 x2
  end;;

end;;

(* Module stubs to prevent direct CakeML API usage *)
(* Users must access these through the Cake module *)
(* Types are re-exported so that pretty printers still work *)

module Alist = struct end;;
module Array = struct end;;
module Bool = struct end;;
module Char = struct end;;
module Command_line = struct end;;
module Double = struct
  type double = Cake.Double.double
end;;
module Hashtable = struct end;;
module Int = struct end;;
module List = struct end;;
module Map = struct end;;
module Marshalling = struct end;;
module Option = struct end;;
module Pair = struct end;;
module Rat = struct
  type rat = Cake.Rat.rat
end;;
module Runtime = struct end;;
module Set = struct end;;
module Sexp = struct end;;
module String = struct end;;
module Vector = struct end;;
module Word64 = struct end;;
module Word8 = struct end;;
module Word8_array = struct end;;

(* End of generated section *)